---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 6-demo-helmrelease-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 6-demo-source-git-bb-app
  interval: 10s
  targetNamespace: 6-demo
  values:
    fullnameOverride: ""
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.6.0
      tag: ""
    imagePullSecrets: []
    labels:
      app:
        env: uat
        name: bb-app
        version: 7.6.0
    nameOverride: ""
    namespace:
      name: 6-demo
    replicaCount: 1
    service:
      port: 80
      targetPort: 80
      type: ClusterIP
