---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 7-demo-kustomization-bb-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./7.7.0/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: 7-demo-source-git-bb-app
  targetNamespace: 7-demo
